"""add_country column

Revision ID: 15452d36195d
Revises: 66960cfdbcb7
Create Date: 2026-04-23 06:29:40.700115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15452d36195d'
down_revision: Union[str, Sequence[str], None] = '66960cfdbcb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('country_probability', sa.Float(), nullable=False))
    op.alter_column('users', 'gender_probability',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using='gender_probability::double precision')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.drop_column('users', 'country_probality')
    op.drop_column('users', 'sample_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sample_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('country_probality', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.alter_column('users', 'gender_probability',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('users', 'country_probability')
    op.drop_column('users', 'country_name')
    # ### end Alembic commands ###
